version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Building the application...
      - npx prisma generate
      - npx prisma migrate deploy
      - npm run build
  post_build:
    commands:
      - echo Build completed successfully.
artifacts:
  files:
    - '**/*'
  base-directory: dist

cache:
  paths:
    - node_modules/**/*